config/routes.rb
Rails.application.routes.draw do
  get 'adminpage/index'

  resources :taxis
  devise_for :users
  get 'home/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/taxi.rb
class Taxi < ApplicationRecord
	has_one :petition
end

app/models/user.rb
class User < ApplicationRecord
	has_many :petitions
  	enum role: [:user, :admin]
	after_initialize :set_default_role, :if => :new_record?
	attr_accessor :name

	def set_default_role
		self.role ||= :user
	end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adminpage_controller.rb
class AdminpageController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?
	protected

	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address, :phone])
	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :phone])
	end
end

app/controllers/home_controller.rb
	class HomeController < ApplicationController
  def index
  end
end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  before_action :set_taxi, only: [:show, :edit, :update, :destroy]

  # GET /taxis
  # GET /taxis.json
  def index
    @taxis = Taxi.all
  end

  # GET /taxis/1
  # GET /taxis/1.json
  def show
  end

  # GET /taxis/new
  def new
    @taxi = Taxi.new
  end

  # GET /taxis/1/edit
  def edit
  end

  # POST /taxis
  # POST /taxis.json
  def create
    @taxi = Taxi.new(taxi_params)

    respond_to do |format|
      if @taxi.save
        format.html { redirect_to @taxi, notice: 'Taxi was successfully created.' }
        format.json { render :show, status: :created, location: @taxi }
      else
        format.html { render :new }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taxis/1
  # PATCH/PUT /taxis/1.json
  def update
    respond_to do |format|
      if @taxi.update(taxi_params)
        format.html { redirect_to @taxi, notice: 'Taxi was successfully updated.' }
        format.json { render :show, status: :ok, location: @taxi }
      else
        format.html { render :edit }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxis/1
  # DELETE /taxis/1.json
  def destroy
    @taxi.destroy
    respond_to do |format|
      format.html { redirect_to taxis_url, notice: 'Taxi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taxi
      @taxi = Taxi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taxi_params
      params.require(:taxi).permit(:name, :services, :status, :rate, :sumkms, :working)
    end
end

app/helpers/adminpage_helper.rb
module AdminpageHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/taxis_helper.rb
module TaxisHelper
end

app/views/adminpage/index.html.erb
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header"><a class="navbar-brand navbar-link" href="#"><i class="glyphicon glyphicon-phone"></i>Tappxy</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active" role="presentation"><a href="#">Home </a></li>
                    <li role="presentation"><a href="#">Quienes somos</a></li>
                    <li role="presentation"><a href="#">Mapa </a></li>
                    <li role="presentation">
                        <a href="#">
                            <button class="btn btn-info btn-xs" type="button">Usuario </button>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="row register-form">
        <div class="col-md-10 col-md-offset-1 col-md-pull-0">
            <h1 class="text-center text-info">Administración </h1>
            <div class="row">
                <div class="col-md-6">
                    <h1 class="text-center text-info">Peticiones </h1></div>
                <div class="col-md-6">
                    <h1 class="text-center text-info">Taxis </h1></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 col-md-offset-1">
            <ul class="list-group">
                <li class="list-group-item"><span>tana@gmail.com - c:/ cacnonigo j. ortega nº:1 piso:1</span></li>
                <li class="list-group-item"><span>Omaro@gmail.com -c:/ la herreria nº:23 piso:3ª</span></li>
            </ul>
        </div>
        <div class="col-md-5">
            <ul class="list-group">
                <li class="list-group-item"><span>id= 25781 </span>
                    <p class="text-success">Libre </p>
                </li>
                <li class="list-group-item"><span>id= 00297 </span>
                    <p class="text-success">Libre </p>
                </li>
                <li class="list-group-item"><span>id= 05672</span>
                    <p class="text-warning">ocupado </p>
                </li>
            </ul>
        </div>
    </div>
    <section class="testimonials"></section>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Tappxi© 2017</h5></div>
                <div class="col-sm-6 social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
            </div>
        </div>
    </footer>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>

<head>
   
</head>

<body class="hero">
    
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6  get-it">
                    <h1>La movilidad que necesitas</h1>
                
                </div>
                <div class="col-md-4 col-md-push-1 phone-preview">
                    <div class="login-card" id="LogDiv">
                    	<%= link_to " <button class= btn btn-primary btn-block btn-info btn-reg> Registrate</button>".html_safe, new_user_registration_path %> 
                    	<%= link_to " <button class= btn btn-primary btn-block btn-warning> Entrar</button>".html_safe, new_user_session_path %> 
        
                    </div>
                
            </div>
        </div>
    </div>
    </div>
    <section class="testimonials"></section>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Tappxi© 2017</h5></div>
                <div class="col-sm-6 social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
            </div>
        </div>
    </footer>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tappxy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="assets/css/user.css">
    <link rel="stylesheet" href="assets/css/Google-Style-Login.css">
    <script type="text/javascript" src="assets\js\jquery.min.js"></script>
    <script type="text/javascript" src="assets\js\jquery.js"></script>
  </head>

  <body>
  	<nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header"><a class="navbar-brand navbar-link" href="#"><i class="glyphicon glyphicon-phone"></i>Tappxi</a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-right navmenu">
                    <li class="active" role="presentation"><a href="#">Home </a></li>
                    <li role="presentation"><a href="#">Quienes somos</a></li>
                    
                    <!--<li role="presentation">-->
                        <a href="#">
                        	<% if current_user %>
                            <button class="btn btn-info btn-xs" type="button" id="UserButton"><%= current_user.email %> </button>
                            <%= link_to " <button class= btn btn-primary btn-block btn-info> Cerrar Sesión</button>".html_safe, destroy_user_session_path, :method => :delete %> 
                            <% end %>
                        </a>
                    <!--</li>-->
                </ul>
            </div>
        </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/taxis/_form.html.erb
<%= form_with(model: taxi, local: true) do |form| %>
  <% if taxi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(taxi.errors.count, "error") %> prohibited this taxi from being saved:</h2>

      <ul>
      <% taxi.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :taxi_name %>
  </div>

  <div class="field">
    <%= form.label :services %>
    <%= form.number_field :services, id: :taxi_services %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status, id: :taxi_status %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.number_field :rate, id: :taxi_rate %>
  </div>

  <div class="field">
    <%= form.label :sumkms %>
    <%= form.number_field :sumkms, id: :taxi_sumkms %>
  </div>

  <div class="field">
    <%= form.label :working %>
    <%= form.check_box :working, id: :taxi_working %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/taxis/edit.html.erb
<h1>Editing Taxi</h1>

<%= render 'form', taxi: @taxi %>

<%= link_to 'Show', @taxi %> |
<%= link_to 'Back', taxis_path %>

app/views/taxis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Taxis</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Services</th>
      <th>Status</th>
      <th>Rate</th>
      <th>Sumkms</th>
      <th>Working</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taxis.each do |taxi| %>
      <tr>
        <td><%= taxi.name %></td>
        <td><%= taxi.services %></td>
        <td><%= taxi.status %></td>
        <td><%= taxi.rate %></td>
        <td><%= taxi.sumkms %></td>
        <td><%= taxi.working %></td>
        <td><%= link_to 'Show', taxi %></td>
        <td><%= link_to 'Edit', edit_taxi_path(taxi) %></td>
        <td><%= link_to 'Destroy', taxi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Taxi', new_taxi_path %>

app/views/taxis/new.html.erb
<h1>New Taxi</h1>

<%= render 'form', taxi: @taxi %>

<%= link_to 'Back', taxis_path %>

app/views/taxis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @taxi.name %>
</p>

<p>
  <strong>Services:</strong>
  <%= @taxi.services %>
</p>

<p>
  <strong>Status:</strong>
  <%= @taxi.status %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @taxi.rate %>
</p>

<p>
  <strong>Sumkms:</strong>
  <%= @taxi.sumkms %>
</p>

<p>
  <strong>Working:</strong>
  <%= @taxi.working %>
</p>

<%= link_to 'Edit', edit_taxi_path(@taxi) %> |
<%= link_to 'Back', taxis_path %>